microsoft/ReSub

package.json
src/ComponentBase.ts
src/Options.ts

This allows for a global override or the Resub.ComponentBase shouldComponentUpdate comparison behaviour
Some people may choose to return true here if their models are not immutable

Allow a non-default shouldComponentUpdateComparator

---

package.json
src/StoreBase.ts

If a store uses deferred triggers, don't bother setting up a deferral if we've determined that there's nothing to trigger on (current or pending)

Small optimization to triggering logic

---

package.json
src/StoreBase.ts
tests/AutoSubscribeTests.tsx

Could not find a declaration file for module 'lodash'. '/src/reactxp/samples/hello-resub/node_modules/lodash/lodash.js' implicitly has an 'any' type.

[0.0.16] Fix error with lodash exported typings

---

package.json
src/StoreBase.ts
tests/StoreBaseTests.ts

This can occur in the case where more than 2 callees are subscribed to a store and unsubscribe during the callback.  If one of the N-1 callees cause the store to trigger again, all the remaining callbacks will be queued and called again.  This will result in some of the callers calling unsubscribe more than once
Add a unit test for this case

[0.0.19] Fix a rare unsubscription error

---

package.json
src/ComponentBase.ts

before setstate instead of _.isEqual
This allows the same logic that compares props in shouldComponentUpdate to be used to determine if we should trigger a new buildState

Use custom shouldComponentUpdateComparator when comparing props 

---

.gitignore
src/ComponentBase.ts
src/Instrumentation.ts
src/StoreBase.ts

StoreBase callbacks and _buildState()s are shown on user timing
timeline along with React 16.0+
It's supported on Web/Electron and while remote debugging RN
with Chrome(v8). Needs Performance.mark() and Performance.measure() 
to be present to work, otherwise it uses noop implementation.

Added Performance API support

---

package.json
src/ComponentBase.ts
src/Options.ts

React error boundaries will make this redundant.

1.0.4: Option to disable "catch in render -> null".

---

src/ComponentBase.ts

Method `_hasMatchingAutoSubscription` uses `.some` in order to check value in `Array` (`_handledAutoSubscriptions`), and in `.some` sets `.used` property. Method contains two different operarions `has` and `set`, I think this is not good in context of single responsibility principle.

Split method _hasMatchingAutoSubscription to several methods

---

src/Instrumentation.ts
src/StoreBase.ts

- Instead of measuring each callback separately in StoreBase we now measure
only how long it takes to execute them all:
- It makes better overview as now we have only one continous block
on timeline.
- We want only high-level overview anyway (details can be still
found in stack trace).
- And in case we have a lot of very fast callbacks we don't distort
results so much by overhead of mark() and measure().
- Better labels for measurements and other small improvements

Instrumentation improvements

---

src/ComponentBase.ts

> Enabling --strict enables --noImplicitAny, --noImplicitThis, --alwaysStrict, --strictNullChecks, --strictFunctionTypes and --strictPropertyInitialization.
> --alwaysStrict - Parse in strict mode and emit "use strict" for each source file

 Remove useless 'use strict'. ts compiler uses 'strict: true' which enables 'alwaysStrict'

---

package.json
src/AutoSubscriptions.ts
src/ComponentBase.ts

Turns out _.bind stringifies the input function and staples onto toString, which can cause un-wanted memory usage

Reduce memory usage in library by removing _.bind usage

---

src/StoreBase.ts
src/lodashMini.ts

`keys` is the array of strings. To copy array we can use some of native methods, like [`.slice`, `[...]` which a little bit faster than  `_.clone`](https://jsfiddle.net/arv1jek7/).

use native .slice method to copy array

---

README.md
src/AutoSubscriptions.ts
src/ComponentDecorators.ts
src/Options.ts
src/ReSub.ts
test/AutoSubscribe.spec.tsx
test/SimpleStore.ts

Update README with new functionality
Additionally, follow React guidance and encourace consumers to optimize shouldComponentUpdate instead of doing deep equality checks on every update

Add the ability to specify comparators for ReSub components via Decorators

---

src/ComponentBase.ts

This fixes the Problem described in https://github.com/Microsoft/ReSub/issues/100.

feat(types): Remove React.Props as generic baseclass for Property of ComponentBase

---

README.md
src/AutoSubscriptions.ts
src/ReSub.ts
src/utils.ts
test/AutoSubscribe.spec.tsx
test/AutoSubscribeWarnings.spec.tsx
test/SimpleStore.ts

Any @autosubscribe with key params are taken as last in the list, and 0 or more @key'd function parameters come first, in left to right argument order.  This lets you have more hierarchical stores with natural function parameters.  From inside the store, you use the new formCompoundKey utility function to trigger compound-key-based triggers.  See the new SimpleStore functions for examples of how to use it.

Building in a system that supports compound keys

---

README.md
src/ComponentBase.ts
src/tslint/incorrectStateAccessRule.ts

This is a companion to https://github.com/microsoft/reactxp/issues/1039
This migration was performed using the recommend codemod tool:
`npx react-codemod rename-unsafe-lifecycles`
https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#renaming-unsafe-lifecycle-methods
The converted code will not work on react versions < v16.3 (react-native v0.55)
The converted code will continue to work on react v17.x
The pro of this PR is that it will stop really ugly warning messages with react >= v16.9 (released yesterday)
The con of this PR is that it just defers the actual cognitive work (and associated breaking change) of the real fix which is migrating to different lifecycle methods, but as discussed in the linked reactxp issue, that is a tradeoff between backwards compatibility earlier than react …

Use new/temporary react lifecycle methods

---

README.md
src/ComponentBase.ts
src/Types.ts
test/AutoSubscribe.spec.tsx

For 2.X we should remove manual subscriptions from components. This is needlessly complex and doesn't provide any measurable additional value
Anyone that needs this functionality can adapt the old code to a new base class in their own project

BREAKING CHANGE: Remove manual component level subscriptions

---

README.md
package.json
src/ComponentBase.ts

This will handle the case where _buildState relies on a value that can be changed by calling setState
Fixes #131

Pass incomingState to _buildState

---

src/ComponentBase.ts

It is easier to check for undefined than to check whether an object has properties or not.
So this fixes the problem, that one must check for every property used via `Object.prototype.hsaOwnProperties.call(state, 'propertyName')`.
Here I assume, that the user does not have to see the internal state inside the buildState function.

fix: this makes state in buildState on initialState undefined

---

README.md
src/StoreBase.ts
test/AutoSubscribe.spec.tsx
test/StoreBase.spec.tsx

There's currently no way to track unkeyed-subscriptions (subscribe() or @autoSubscribe without a key passed) starting and stopping in your store.  Adding the ability to do so.  Eventually, we'll stop using _started/stoppedTrackingKey, since the new callbacks are a superset of that functionality.  But adding these separately since it's a breaking change from behavior used in the past.  Also added a unit test for both sets of callbacks since apparently we never did that before.  Woopsie.

Adding _startedTrackingSub/_stoppedTrackingSub callbacks
